site_name: Traffic Analysis Train

theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  icon:
  logo: 'assets/logo_white.png'
  favicon: 'assets/favicon.ico'


extra:
  search:
    language: 'jp'

repo_url: https://github.com/satan1a/traffic-analysis-train
repo_name: Toky/TrafficAnalysis